AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - in.mshitlearner::springboot_aws_serverless
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  Springboot_aws_serverlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: in.mshitlearner.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  Springboot_aws_serverlessApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: Springboot_aws_serverlessApi
